# Generated by Django 5.1 on 2025-03-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservation_number_of_persons'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('last_name', 'date_booking', 'email')},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]
