# Generated by Django 5.1 on 2025-03-08 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('first_name', 'last_name', 'date_booking')},
        ),
    ]
