# Generated by Django 5.1 on 2025-03-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('last_name', 'date_booking', 'email')},
        ),
    ]
