# Generated by Django 5.1 on 2024-09-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
