# Generated by Django 5.1 on 2024-12-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
