# Generated by Django 5.1 on 2024-12-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_alter_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='media/images/default.jpg', upload_to=''),
        ),
    ]
