# Generated by Django 5.1 on 2024-12-20 10:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_alter_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=cloudinary.models.CloudinaryField(default='images/default.png', max_length=255, verbose_name='image'),
        ),
    ]
